### ISSUE TITLE
Filenaming

### ISSUE THREAD

**Issue by github1educorg1com** [Staubteufel/BulkPDF#10]
for filenaming can you add morethan one from DataSource column?

<Filename>
      <Prefix>_</Prefix>
      <ValueFromDataSource>True</ValueFromDataSource>
      <DataSource>sheet1[.]Department  + sheet1[.]firstname </DataSource>
      <Suffix>_</Suffix>
      <RowNumber>True</RowNumber>
    </Filename>

**Comment by Tadelsucht** [comment]
No, I do not intend to advance the file naming with this feature. You could easily make a filename column in your excel file to have the same result.
