### ISSUE TITLE
AcroForm not filling in values

### ISSUE THREAD

**Issue by ldub** [Staubteufel/BulkPDF#12]
When I am trying to bulk fill a PDF form that is an XFA form, it completes successfully but the resulting PDF is empty. 

I was able to fix it by changing SaveFilledPDF to do:

```pdfStamper.AcroFields.SetField(field.Name, field.Value);```

instead of inserting a new text node as it does now. But I don't know if that is the proper way of filling the text fields.

Do you have a Unit test suite or something where I can add a repro for this?

**Comment by Tadelsucht** [comment]
I am afraid to tell you, that I do not have any test for BulkPDF. I have made this program way before I know anything about the practical use of unit test. Also the code is a mess.
You could create a pull request with your change(s). As long is it still compile and the embedded example files still work with BulkPDF, I will accept the changes.
