### ISSUE TITLE
Silent uninstallation

### ISSUE THREAD

**Issue by Saxomania** [Staubteufel/BulkPDF#16]
Hi,

thanks to Julien for his work. May i am blind but i do not find the right argument for a silent uninstallation.

Silent install is working with /S but for uninstallation the "default" arguments do not work.

**Comment by Saxomania** [comment]
just for information i tried it with:

C:\Program Files (x86)\BulkPDF\uninst.exe and the arguments

/S
/Silent
/Verysilent
/Q
/A

and the same arguemnts with lower case also

**Comment by Tadelsucht** [comment]
I don't have any idea how to silently uninstall BulkPDF. The installer is made with https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System maybe there are default options for this case(?).

Besides my lack of knowledge, why you don't just use the portable version, which can be easily silently deleted?

**Comment by Saxomania** [comment]
Nullsoft uses /S like it works for the silent install. I want to have it in the control panel -> programs & features listed thats why i prefer an installation 

by the way: your documentations says its for version 1.0.3.0 but program is now 1.1.0.0. is there any change which is important for documentation?

**Comment by Tadelsucht** [comment]
Ok, but I have no intend to check the silent uninstall functionality. But you can write your own installer🤷‍♂️

Not really, except that a higher .NET Framework Version ist used, which could be a problem on Windows XP, Vista and maybe 7.
