### ISSUE TITLE
Cyrilic is not supported

### ISSUE THREAD

**Issue by Aleksandar1932** [Staubteufel/BulkPDF#19]
Bulk form filling is not possible with cyrilic values for the fields.

**Comment by Tadelsucht** [comment]
[BulkPDF.zip](https://github.com/Tadelsucht/BulkPDF/files/6177248/BulkPDF.zip)
Please try this preview of version 1.2 with unicode support.

**Comment by Aleksandar1932** [comment]
Now it works, thanks.

**Comment by Tadelsucht** [comment]
@Aleksandar1932 Try the newest release. In the old one I accidently removed the save configuration button.
