### ISSUE TITLE
GNU/Linux operating system support via Flathub

### ISSUE THREAD

**Issue by ovari** [Staubteufel/BulkPDF#24]
Is it possible to run your program natively on GNU/Linux operating systems?

For example, [Linux Mint](https://linuxmint.com/) Cinnamon?

Could your program please be added to [Flathub](https://flathub.org/)?

What do you think?

Thank you

**Comment by Tadelsucht** [comment]
No.

Maybe with wine.

No.

I don't think that a linux user needed this software right now.
