### ISSUE TITLE
custom splash screen

### ISSUE THREAD

**Issue by divansantana** [Staubteufel/BulkPDF#28]
Any way to pass in an argument to change or supress/silence the splash screen, ie suppress 
'free open source software' or 'bulkpdf'

**Comment by Tadelsucht** [comment]
No. You can change the software, but you must respect the license. ( https://github.com/Tadelsucht/BulkPDF/blob/master/LICENSE.txt )
If you want a special version for a costumer, we could discuss a solution with BulkPDF Business ( https://bulkpdf.de/landingpage-en ).

[support@bulkpdf.de](https://bulkpdf.de/support/en)
