### ISSUE TITLE
Can not handle date fields

### ISSUE THREAD

**Issue by Tadelsucht** [Staubteufel/BulkPDF#5]
From a support mail:
"My date field on my form is filling only with the numeric number for the date rather than the date when importing with bulkpdf. I have the field in excel formatted for date and the field on my pdf formatted for date."

Answer:
"BulkPDF can not handle date fields. You must change the field type to text."

**Comment by kyleheyne** [comment]
I had this problem and used the following formula to create a new column that contains dates in text format. Depending on your requirements you may need to change the format to something else.

`=TEXT(CELL_REFERENCE, "MM/DD/YYYY")`

**Comment by Tadelsucht** [comment]
Thanks for sharing your workaround 👍
