### ISSUE TITLE
How to fill in radio buttons, check boxes, etc. based on values in Excel?

### ISSUE THREAD

**Issue by sergeiwallace** [Staubteufel/BulkPDF#7]
How can I fill in radio buttons, check boxes, etc. based on values in Excel? I tried to do it based on "YES" or 0/1 values but it didn't work. 

Also, some radio buttons actually have two buttons in one field (yes box and no box, etc.) and it seems like the BulkPDF software only picked up one of the individual radio buttons, and so even if it did work, it would only be able to turn on/off one of the two buttons.

**Comment by Tadelsucht** [comment]
Do you have an example PDF and Excel file, which you could share for analyse?

The value to tick the check boxes depends on the language, which is used in the PDF form. So in german the values would be "Ja" und "Nein".
On the following website you can find out the neccessary values for the check boxes in your PDF file: https://www.pdfescape.com/

**Comment by yudadude** [comment]
having the same problem cannot fill the checkbox tried all the above not working
see attached excel file 
[sunday 12-30.xlsx](https://github.com/Tadelsucht/BulkPDF/files/1596551/sunday.12-30.xlsx)

**Comment by Tadelsucht** [comment]
@yudadude 
Have you tried to analyse your pdf file with the pdfescape.com?
Which neccessary values for the check boxes does the website say?

**Comment by github1educorg1com** [comment]
can you add more than one filename from datasource row?

<Filename>
      <Prefix>_</Prefix>
      <ValueFromDataSource>True</ValueFromDataSource>
      <DataSource>sheet1[.]Department  +sheet1[.]firstname </DataSource>
      <Suffix>_</Suffix>
      <RowNumber>True</RowNumber>
    </Filename>
